from __future__ import annotations

import re
from copy import deepcopy
from datetime import datetime
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple
from uuid import uuid4

from docx import Document
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.table import Table
from docx.text.paragraph import Paragraph

from srs_generator.models import SRSProject, StructuredRequirement
from srs_generator.section_instructions import PROJECT_FIELD_LABELS, PROJECT_SECTION_INSTRUCTIONS
from srs_generator.utils import safe_filename
from srs_generator.validator import SRSValidator


class SrsTemplateRenderer:
    """Render SRSProject JSON into a DOCX master template while preserving XML styles."""

    def __init__(self, template_path: str | Path = "srs_generator/templates/srs_template.docx") -> None:
        self.template_path = Path(template_path)

    def render_to_bytes(self, project: SRSProject) -> bytes:
        output_path = Path("/tmp") / f"{safe_filename(project.project_name)}_{uuid4().hex}_srs.docx"
        self.render(project, output_path)
        data = output_path.read_bytes()
        try:
            output_path.unlink()
        except OSError:
            pass
        return data

    def render(self, project: SRSProject, output_path: str | Path | None = None) -> Path:
        if not self.template_path.exists():
            raise FileNotFoundError(f"SRS template not found: {self.template_path}")

        document = Document(self.template_path)
        self._replace_global_placeholders(document, project)
        self._replace_section_placeholder(document, {"Purpose of the Document"}, self._project_section_value(project, "purpose"))
        self._replace_section_placeholder(document, {"Intended Audience"}, self._project_section_value(project, "intended_audience"))
        self._replace_section_placeholder(document, {"Overview", "System Overview"}, self._project_section_value(project, "system_overview"))
        self._replace_section_placeholder(document, {"Scope"}, self._project_section_value(project, "scope"))
        self._replace_section_placeholder(document, {"Operating environment"}, self._project_section_value(project, "operating_environment"))
        self._replace_section_placeholder(document, {"Overall Acceptance Criteria"}, self._project_section_value(project, "acceptance_criteria"))

        self._render_functional_requirements(document, project)
        self._render_requirement_management_table(document, project.requirements)
        self._neutralize_unused_requirement_placeholders(document)
        self._cleanup_remaining_angle_instructions(document)

        document.core_properties.title = project.document_title
        document.core_properties.subject = project.project_name
        document.core_properties.comments = "Generated by SRS Intelligence Pipeline"
        document.core_properties.modified = datetime.utcnow()

        if output_path is None:
            output_path = Path("srs_generator/output_docs") / f"{safe_filename(project.project_name)}_SRS.docx"
        output = Path(output_path)
        output.parent.mkdir(parents=True, exist_ok=True)
        document.save(output)
        return output

    def _replace_global_placeholders(self, document: Document, project: SRSProject) -> None:
        replacements = {
            "<Project Name>": project.project_name,
            "{{project_name}}": project.project_name,
            "{{version}}": project.version,
            "{{system_overview}}": project.system_overview,
            "{{scope}}": project.scope,
            "{{acceptance_criteria}}": project.acceptance_criteria,
        }

        previous_text = ""
        for paragraph in document.paragraphs:
            if previous_text.strip().lower() == "software requirement specification" and "<" in paragraph.text:
                self._set_paragraph_text(paragraph, project.project_name)
            for needle, value in replacements.items():
                if needle in paragraph.text:
                    self._replace_paragraph_text(paragraph, needle, value)
            if paragraph.text.strip():
                previous_text = paragraph.text

        for table in document.tables:
            for row in table.rows:
                for cell in row.cells:
                    for paragraph in cell.paragraphs:
                        for needle, value in replacements.items():
                            if needle in paragraph.text:
                                self._replace_paragraph_text(paragraph, needle, value)

    def _project_section_value(self, project: SRSProject, field: str) -> str:
        value = getattr(project, field, "")
        text = str(value or "").strip()
        if field == "intended_audience" and text == SRSValidator.DEFAULT_INTENDED_AUDIENCE:
            text = ""
        if text and text != "Not specified." and not self._has_angle_instruction(text):
            return text
        label = PROJECT_FIELD_LABELS.get(field, field.replace("_", " ").title())
        instruction = PROJECT_SECTION_INSTRUCTIONS.get(field, "")
        if instruction:
            return f"Pending user input: {label}.\n\nExpected information:\n{instruction}"
        return f"Pending user input: {label}."

    def _render_functional_requirements(self, document: Document, project: SRSProject) -> None:
        requirements = project.requirements or [
            StructuredRequirement(
                logical_block="General",
                req_id="AUTO_REQ_001",
                purpose="No explicit requirements were extracted from the source document.",
            )
        ]
        grouped = self._group_requirements(requirements)
        first_group = next(iter(grouped.keys()), "Generated Requirements")
        self._replace_heading_text(document, "<Logical Block>", first_group)

        template_table = self._find_functional_requirement_table(document)
        if template_table is None:
            self._append_requirement_tables(document, grouped)
            return

        template_xml = deepcopy(template_table._element)
        previous_element = template_table._element
        first = True

        for group_name, group_requirements in grouped.items():
            if not first:
                previous_element = self._insert_paragraph_after(previous_element, group_name, "Heading2")
                previous_element = self._insert_paragraph_after(previous_element, "Requirements", "Heading3")
            for req in group_requirements:
                if first:
                    table = template_table
                    first = False
                else:
                    cloned_xml = deepcopy(template_xml)
                    previous_element.addnext(cloned_xml)
                    table = Table(cloned_xml, document)
                self._fill_requirement_table(table, req)
                previous_element = table._element

    def _append_requirement_tables(self, document: Document, grouped: Dict[str, List[StructuredRequirement]]) -> None:
        for group_name, requirements in grouped.items():
            document.add_heading(group_name, level=2)
            document.add_heading("Requirements", level=3)
            for req in requirements:
                table = document.add_table(rows=0, cols=2)
                for label, value in self._requirement_rows(req):
                    cells = table.add_row().cells
                    cells[0].text = label
                    cells[1].text = value

    def _fill_requirement_table(self, table: Table, req: StructuredRequirement) -> None:
        values = {self._normalize_label(label): value for label, value in self._requirement_rows(req)}
        for row in table.rows:
            if len(row.cells) < 2:
                continue
            label_key = self._normalize_label(row.cells[0].text)
            value = self._value_for_label(label_key, values, req)
            if value is not None:
                self._set_cell_text(row.cells[1], value)

    def _requirement_rows(self, req: StructuredRequirement) -> List[Tuple[str, str]]:
        return [
            ("REQ ID", req.req_id),
            ("Customer Req ID", req.metadata.customer_req_id or ""),
            ("Milestone", req.metadata.milestone or ""),
            ("Purpose1", req.purpose),
            ("Derived Requirement", req.derived_requirement),
            ("Requirement Priority", req.metadata.priority or "Medium"),
            ("Access Restrictions", req.access_restrictions),
            ("Input(s)", req.inputs),
            ("Output(s)", req.outputs),
            ("Process", req.process),
            ("Mandatory Fields", req.mandatory_fields),
            ("Validation Rules/ Verification criteria2", req.validation),
            ("Constraints", req.constraints),
            ("Assumptions", req.assumptions),
            ("Failure Scenario", req.failure_scenario),
            ("Action if Failure", req.action_on_failure),
            ("Acceptance Criteria", req.acceptance_criteria),
            ("Requirement Acceptance Criteria", req.acceptance_criteria),
            ("Requirement Status", req.status),
            ("Critical", self._bool_text(req.critical)),
            ("Feasible", self._bool_text(req.feasible)),
            ("Comments", req.comments),
        ]

    def _value_for_label(self, label_key: str, values: Dict[str, str], req: StructuredRequirement) -> Optional[str]:
        if label_key in values:
            return values[label_key]
        if "req id" in label_key:
            return req.req_id
        if "purpose" in label_key or "description" in label_key:
            return req.purpose
        if "input" in label_key:
            return req.inputs
        if "output" in label_key:
            return req.outputs
        if "process" in label_key:
            return req.process
        if "validation" in label_key or "verification" in label_key:
            return req.validation
        if "acceptance" in label_key:
            return req.acceptance_criteria
        if "critical" in label_key:
            return self._bool_text(req.critical)
        if "feasible" in label_key:
            return self._bool_text(req.feasible)
        if "comment" in label_key or "rationale" in label_key:
            return req.comments
        return None

    def _render_requirement_management_table(self, document: Document, requirements: List[StructuredRequirement]) -> None:
        table = self._find_requirement_management_table(document)
        if table is None or not requirements:
            return
        while len(table.rows) > 1:
            table._tbl.remove(table.rows[-1]._tr)
        for req in requirements:
            cells = table.add_row().cells
            values = [
                req.req_id,
                req.logical_block,
                req.requirement_type,
                req.metadata.priority or "Medium",
                req.status,
                f"{req.metadata.confidence:.2f}",
            ]
            for idx, value in enumerate(values[: len(cells)]):
                cells[idx].text = value

    def _neutralize_unused_requirement_placeholders(self, document: Document) -> None:
        placeholder_ids = {"rq0n", "requirement description", "<cs-req-001>", ""}
        for table in document.tables:
            req_id_value = None
            for row in table.rows:
                if len(row.cells) < 2:
                    continue
                if self._normalize_label(row.cells[0].text) in {"req id", "requirement id"}:
                    req_id_value = self._normalize_label(row.cells[1].text)
                    break
            if req_id_value not in placeholder_ids and not self._is_placeholder_value(req_id_value or ""):
                continue

            for row in table.rows:
                if len(row.cells) < 2:
                    continue
                label = self._normalize_label(row.cells[0].text)
                if label in {"req id", "requirement id"}:
                    self._set_cell_text(row.cells[1], "N/A")
                elif label and label != "term":
                    self._set_cell_text(row.cells[1], "Not applicable.")

    def _is_placeholder_value(self, value: str) -> bool:
        text = self._normalize_label(value)
        placeholder_phrases = (
            "map functional requirement id here",
            "mention safety requirement id here",
            "from which phase the requirement is identified",
            "a precise and unambiguous statement",
            "purpose of the functionality",
        )
        return any(phrase in text for phrase in placeholder_phrases)

    def _replace_section_placeholder(self, document: Document, heading_names: set[str], value: str) -> None:
        if not value or value == "Not specified.":
            return
        normalized_headings = {self._clean_heading_name(name) for name in heading_names}
        capture_next = False
        start_level = None
        replaced = False
        for paragraph in document.paragraphs:
            text = paragraph.text.strip()
            paragraph_level = self._paragraph_heading_level(paragraph)
            if capture_next and paragraph_level and start_level and paragraph_level <= start_level:
                return
            if capture_next and ("<" in text or not text):
                self._set_paragraph_text(paragraph, value if not replaced else "")
                replaced = True
                continue
            if self._clean_heading_name(text) in normalized_headings:
                capture_next = True
                start_level = paragraph_level or 9

    def _replace_heading_text(self, document: Document, old_text: str, new_text: str) -> None:
        for paragraph in document.paragraphs:
            if old_text in paragraph.text:
                self._set_paragraph_text(paragraph, paragraph.text.replace(old_text, new_text))
                return

    def _cleanup_remaining_angle_instructions(self, document: Document) -> None:
        for paragraph in document.paragraphs:
            if self._has_angle_instruction(paragraph.text):
                self._set_paragraph_text(paragraph, "")
        for table in document.tables:
            for row in table.rows:
                for cell in row.cells:
                    if self._has_angle_instruction(cell.text):
                        self._set_cell_text(cell, "Not applicable.")

    def _has_angle_instruction(self, text: str) -> bool:
        return "<" in (text or "") and ">" in (text or "")

    def _find_functional_requirement_table(self, document: Document) -> Optional[Table]:
        for table in document.tables:
            labels = [self._normalize_label(row.cells[0].text) for row in table.rows if row.cells]
            joined = " ".join(labels[:12])
            if "req id" in labels and "purpose1" in labels and ("input(s)" in labels or "process" in labels):
                return table
            if "req id" in joined and "purpose" in joined and "process" in joined:
                return table
        return None

    def _find_requirement_management_table(self, document: Document) -> Optional[Table]:
        for table in document.tables:
            if not table.rows or len(table.rows[0].cells) < 3:
                continue
            headers = [self._normalize_label(cell.text) for cell in table.rows[0].cells]
            if "req id" in headers[0] and any("priority" in header for header in headers):
                return table
        return None

    def _group_requirements(self, requirements: Iterable[StructuredRequirement]) -> Dict[str, List[StructuredRequirement]]:
        grouped: Dict[str, List[StructuredRequirement]] = {}
        for req in requirements:
            grouped.setdefault(req.logical_block or "General", []).append(req)
        return grouped

    def _insert_paragraph_after(self, element, text: str, style_id: str):
        paragraph = OxmlElement("w:p")
        p_pr = OxmlElement("w:pPr")
        p_style = OxmlElement("w:pStyle")
        p_style.set("{http://schemas.openxmlformats.org/wordprocessingml/2006/main}val", style_id)
        p_pr.append(p_style)
        paragraph.append(p_pr)
        run = OxmlElement("w:r")
        text_element = OxmlElement("w:t")
        text_element.text = text
        run.append(text_element)
        paragraph.append(run)
        element.addnext(paragraph)
        return paragraph

    def _replace_paragraph_text(self, paragraph: Paragraph, needle: str, value: str) -> None:
        self._set_paragraph_text(paragraph, paragraph.text.replace(needle, value))

    def _set_paragraph_text(self, paragraph: Paragraph, text: str) -> None:
        p_element = paragraph._p
        for child in list(p_element):
            if child.tag != qn("w:pPr"):
                p_element.remove(child)
        if text:
            paragraph.add_run(text)

    def _set_cell_text(self, cell, text: str) -> None:
        if cell.paragraphs:
            self._set_paragraph_text(cell.paragraphs[0], text)
            for paragraph in cell.paragraphs[1:]:
                self._set_paragraph_text(paragraph, "")
        else:
            cell.text = text

    def _normalize_label(self, value: str) -> str:
        return " ".join((value or "").replace("\n", " ").strip().lower().split())

    def _clean_heading_name(self, value: str) -> str:
        text = self._normalize_label(value)
        return re.sub(r"^\d+(?:\.\d+)*\.?\s*", "", text)

    def _paragraph_heading_level(self, paragraph: Paragraph) -> Optional[int]:
        style_name = paragraph.style.name if paragraph.style is not None else ""
        match = re.search(r"heading\s+(\d+)", style_name, flags=re.I)
        return int(match.group(1)) if match else None

    def _bool_text(self, value: bool | None) -> str:
        if value is True:
            return "Yes"
        if value is False:
            return "No"
        return "Not specified."
